language: go

go:
  - "1.10"

sudo: false

git:
  depth: 10

branches:
  only:
    - source
  except:
    - master

install:
  - go get -u -v github.com/spf13/hugo

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_TOKEN}
  local-dir: public
  target-branch: master
  on:
    branch: source
