baseURL = "https://avelino.run/"
languageCode = "en-us"
title = "Avelino"
theme = "sarah"
googleAnalytics = "UA-3063031-15"
disqusShortname = "avelino"

[permalinks]
fixed = ":title/"
blog  = ":slug"

[params]
author = "Avelino"
keywords = ["Racket", "Go (Gopher)", "Clojure", "Neural Network", "Artificial Intelligence"]
avatar = "img/2018-09-run.png"
dateform = "Jan 2, 2006"
lang = "en"
footertext = "written by avelino"
about = """
I’m **Thiago Avelino** engineer/founder at [Nuveo](https://nuveo.ai/) (**Artificial Intelligence** within reach), [levpay](https://levpay.com) (*JV between Nuveo and Banco Rendimento (Brazilian Bank)*) and Mathematician at [IME-USP - Aplicated Math](https://www.ime.usp.br/).

Work day-to-day with **artificial intelligence, neural network and computer vision**. With the need to process large dataset its focus of research and development include **distributed systems, competition, Clojure (lisp dialects), Golang and Python**.
"""

[params.social]
instagram     = "avelinorun"
github        = "avelino"
twitter       = "avelinorun"
linkedin      = "avelinorun"
# googleplus    = "thiagoavelino"

[[params.info]]
label = "Email"
value = "t AT avelino DOT xxx"
link = "mailto:t@avelino.xxx"

[[params.info]]
label = "Address"
value = "Brazil, São Paulo, SP"

[[params.projects]]
name = "Vim Bootstrap"
desc = "A generator which provides a simple method of generating a .vimrc configuration for vim"
img = "img/vimbootstrap.png"
link = "https://vim-bootstrap.com/"

[[params.projects]]
name = "Awesome Go"
desc = "A curated list of awesome Go frameworks, libraries and software"
img = "img/awesomego.png"
link = "https://awesome-go.com/"

[[params.projects]]
name = "cover.run"
desc = "A code coverage of any golang package as a service"
img = "img/coverrun.png"
link = "https://cover.run/"

[[params.projects]]
name = "Test After Deploy"
desc = "YouTube channel on software development (and its ecosystem)"
img = "img/tad.png"
link = "https://www.youtube.com/channel/UCZCoLtEGz3MdvxgFhbdZ-QA/featured"

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
